/*
 * beatle-nes-redux cartridge: iNES parsing + mappers 0 (NROM), 1 (MMC1),
 * 2 (UNROM), 3 (CNROM), 4 (MMC3).
 *
 * MMC3 IRQ: the counter is clocked on rising edges of the CHR A12 line as
 * generated by the PPU's background pattern fetches during rendering.
 * This models the fetch pattern (not the exact dot timing, and without the
 * hardware A12 filter) — documented approximation.
 */
#include "nes.h"

#include <stdlib.h>
#include <string.h>

void nes_cart_init(nes_cart *c)
{
    memset(c, 0, sizeof *c);
}

void nes_cart_free(nes_cart *c)
{
    free(c->prg);
    free(c->chr);
    free(c->prg_ram);
    memset(c, 0, sizeof *c);
}

emu_result_t nes_cart_load(nes_cart *c, const uint8_t *data, size_t size)
{
    nes_cart_free(c);
    if (size < 16u)
        return EMU_EBADROM;
    if (data[0] != 'N' || data[1] != 'E' || data[2] != 'S' || data[3] != 0x1Au)
        return EMU_EBADROM;

    uint32_t prg_banks = data[4];
    uint32_t chr_banks = data[5];
    uint8_t flags6 = data[6];
    uint8_t flags7 = data[7];
    if (prg_banks == 0u)
        return EMU_EBADROM;

    uint8_t mapper = (uint8_t)(((flags7 & 0xF0u)) | (flags6 >> 4));
    uint8_t mirroring = (uint8_t)((flags6 & 8u) ? 2u : (flags6 & 1u)); /* 2 = four-screen (treated as vertical) */

    size_t prg_size = (size_t)prg_banks * 0x4000u;
    size_t chr_size = (size_t)chr_banks * 0x2000u;
    size_t trainer = (flags6 & 4u) ? 512u : 0u;
    if (size < 16u + trainer + prg_size + chr_size)
        return EMU_EBADROM;

    /* supported mapper subset */
    static const uint8_t supported[] = { 0, 1, 2, 3, 4 };
    int ok = 0;
    for (size_t i = 0; i < sizeof supported; i++)
        if (supported[i] == mapper)
            ok = 1;
    if (!ok)
        return EMU_EUNSUPPORTED;

    c->prg = malloc(prg_size);
    if (c->prg == NULL)
        return EMU_EINVAL;
    memcpy(c->prg, &data[16 + trainer], prg_size);
    c->prg_size = prg_size;
    c->prg_banks = prg_banks;

    if (chr_size == 0u) {
        c->chr_size = 0x2000u;
        c->chr = malloc(c->chr_size);
        if (c->chr == NULL) {
            nes_cart_free(c);
            return EMU_EINVAL;
        }
        memset(c->chr, 0, c->chr_size);
        c->chr_ram = 1;
    } else {
        c->chr = malloc(chr_size);
        if (c->chr == NULL) {
            nes_cart_free(c);
            return EMU_EINVAL;
        }
        memcpy(c->chr, &data[16 + trainer + prg_size], chr_size);
        c->chr_size = chr_size;
        c->chr_ram = 0;
    }

    c->prg_ram = malloc(0x2000u);
    if (c->prg_ram == NULL) {
        nes_cart_free(c);
        return EMU_EINVAL;
    }
    memset(c->prg_ram, 0, 0x2000u);

    c->mapper = mapper;
    c->mirroring = (uint8_t)(mirroring == 2u ? 1u : mirroring);
    nes_cart_reset(c);
    return EMU_OK;
}

void nes_cart_reset(nes_cart *c)
{
    c->mmc1_shift = 0;
    c->mmc1_shift_count = 0;
    memset(c->mmc1_regs, 0, sizeof c->mmc1_regs);
    c->mmc1_regs[3] = 0x0C; /* MMC1 default: 16K fixed at C000, bank 0 low? */
    c->prg_bank = 0;
    c->chr_bank = 0;
    c->mmc3_reg_select = 0;
    memset(c->mmc3_regs, 0, sizeof c->mmc3_regs);
    c->mmc3_regs[6] = 0x80; /* placeholder: overwritten below */
    c->mmc3_regs[6] = 0x00;
    c->mmc3_regs[7] = 0x01;
    c->mmc3_irq_latch = 0;
    c->mmc3_irq_counter = 0;
    c->mmc3_irq_reload_pending = 0;
    c->mmc3_irq_enable = 0;
    c->mmc3_irq_asserted = 0;
    c->mmc3_a12_prev = 0;
}

/* ---- mapper register writes ---- */

static void mmc1_commit(nes_cart *c, uint8_t reg, uint8_t val)
{
    c->mmc1_regs[reg] = val;
}

static void mmc1_write(nes_cart *c, uint16_t addr, uint8_t v)
{
    if (v & 0x80u) {
        c->mmc1_shift_count = 0;
        c->mmc1_shift = 0;
        c->mmc1_regs[0] |= 0x0Cu; /* reset to PRG mode 3 */
        return;
    }
    c->mmc1_shift = (uint8_t)((c->mmc1_shift >> 1) | ((v & 1u) << 4));
    if (++c->mmc1_shift_count >= 5) {
        uint16_t addr_group = (uint16_t)((addr >> 13) & 3u); /* 0..3 */
        mmc1_commit(c, (uint8_t)addr_group, (uint8_t)(c->mmc1_shift & 0x1Fu));
        c->mmc1_shift_count = 0;
        c->mmc1_shift = 0;
    }
}

static void mmc3_write(nes_cart *c, uint16_t addr, uint8_t v)
{
    if (addr <= 0x9FFFu) {
        if ((addr & 1u) == 0u) {
            c->mmc3_reg_select = (uint8_t)(v & 7u);
        } else {
            uint8_t r = c->mmc3_reg_select;
            if (r >= 6u)
                c->mmc3_regs[r] = (uint8_t)(v & 0x3Fu);
            else
                c->mmc3_regs[r] = v;
        }
        return;
    }
    if (addr <= 0xBFFFu) {
        /* $A000 bit0: nametable mirroring (0 = horizontal, 1 = vertical);
         * $A001 PRG RAM protect is not implemented (documented) */
        if ((addr & 1u) == 0u)
            c->mirroring = (uint8_t)(v & 1u);
        return;
    }
    if (addr <= 0xDFFFu) {
        if (addr & 1u)
            c->mmc3_irq_reload_pending = 1;
        else
            c->mmc3_irq_latch = v;
        return;
    }
    if (addr & 1u) {
        c->mmc3_irq_enable = 1;
    } else {
        c->mmc3_irq_enable = 0;
        c->mmc3_irq_asserted = 0;
    }
}

void nes_cart_cpu_write(nes_cart *c, uint16_t addr, uint8_t v)
{
    if (addr < 0x8000u)
        return;
    switch (c->mapper) {
    case 1: mmc1_write(c, addr, v); break;
    case 2: c->prg_bank = (uint8_t)(v & 0x0Fu); break;
    case 3: c->chr_bank = (uint8_t)(v & 0x03u); break;
    case 4: mmc3_write(c, addr, v); break;
    default: break; /* NROM: writes to ROM ignored (bus conflicts not modeled) */
    }
}

/* ---- CPU PRG reads ---- */

static uint32_t prg_bank_count(const nes_cart *c)
{
    return c->prg_banks; /* 16 KiB units */
}

static uint8_t prg_read_bank(nes_cart *c, uint32_t bank16, uint16_t addr)
{
    uint32_t b = bank16 % prg_bank_count(c);
    return c->prg[(size_t)b * 0x4000u + (addr & 0x3FFFu)];
}

uint8_t nes_cart_cpu_read(nes_cart *c, uint16_t addr)
{
    if (c->prg == NULL || c->prg_size == 0)
        return 0xFFu; /* no cartridge mapped */
    switch (c->mapper) {
    case 1: {
        uint8_t prg_mode = (uint8_t)((c->mmc1_regs[0] >> 2) & 3u);
        uint32_t r3 = c->mmc1_regs[3] & 0x0Fu;
        if (prg_mode == 3u) { /* 16K fixed C000, 16K switchable 8000 */
            if (addr < 0xC000u)
                return prg_read_bank(c, r3, addr);
            return prg_read_bank(c, prg_bank_count(c) - 1u, addr);
        }
        /* 32K mode: banks (r3 & ~1, r3 | 1) */
        if (addr < 0xC000u)
            return prg_read_bank(c, (r3 & 0xFEu), (uint16_t)(addr - 0x8000u));
        return prg_read_bank(c, (r3 | 1u), (uint16_t)(addr - 0xC000u));
    }
    case 2:
        if (addr < 0xC000u)
            return prg_read_bank(c, c->prg_bank, (uint16_t)(addr - 0x8000u));
        return prg_read_bank(c, prg_bank_count(c) - 1u, (uint16_t)(addr - 0xC000u));
    case 4: {
        uint8_t prg_mode = (uint8_t)((c->mmc3_regs[0] & 0x40u) ? 1u : 0u);
        uint32_t last = prg_bank_count(c) - 1u;
        if (addr < 0xA000u) {
            uint32_t b = prg_mode ? (uint32_t)c->mmc3_regs[7] : (uint32_t)c->mmc3_regs[6];
            if (!prg_mode && b == last)
                b = last; /* R6 may point at the fixed bank; allow */
            return prg_read_bank(c, b, (uint16_t)(addr - 0x8000u));
        }
        if (addr < 0xC000u)
            return prg_read_bank(c, (uint32_t)c->mmc3_regs[7], (uint16_t)(addr - 0xA000u));
        return prg_read_bank(c, prg_mode ? (uint32_t)c->mmc3_regs[6] : last,
                             (uint16_t)(addr - 0xC000u));
    }
    default: { /* 0 (NROM) and 3 (CNROM): standard PRG mapping */
        return c->prg[(addr - 0x8000u) & (c->prg_size - 1u)];
    }
    }
}

/* ---- CHR access (with MMC3 A12 edge detection) ---- */

static void mmc3_chr_clock(nes_cart *c, uint16_t addr)
{
    uint8_t a12 = (uint8_t)((addr & 0x1000u) != 0u);
    /* counter reload takes effect on the next A12 edge */
    if (a12 && !c->mmc3_a12_prev) {
        if (c->mmc3_irq_reload_pending) {
            c->mmc3_irq_reload_pending = 0;
            c->mmc3_irq_counter = c->mmc3_irq_latch;
        } else if (c->mmc3_irq_counter == 0u) {
            c->mmc3_irq_counter = c->mmc3_irq_latch;
            if (c->mmc3_irq_enable)
                c->mmc3_irq_asserted = 1;
        } else {
            c->mmc3_irq_counter--;
            if (c->mmc3_irq_counter == 0u && c->mmc3_irq_enable)
                c->mmc3_irq_asserted = 1;
        }
    }
    c->mmc3_a12_prev = a12;
}

uint8_t nes_cart_chr_read(nes_cart *c, uint16_t addr)
{
    addr &= 0x1FFFu;
    if (c->mapper == 4)
        mmc3_chr_clock(c, addr);

    size_t offset;
    if (c->mapper == 4) {
        /* slots: R0,R1 are 2 KiB banks; R2..R5 are 1 KiB banks.
         * chr_mode 0: R0@0000-07FF R1@0800-0FFF R2..R5@1000-1FFF
         * chr_mode 1: R2..R5@0000-0FFF R0@1000-17FF R1@1800-1FFF */
        uint8_t chr_mode = (uint8_t)((c->mmc3_regs[0] & 0x80u) ? 1u : 0u);
        uint32_t slot;
        uint16_t intra;
        if (chr_mode == 0u) {
            if (addr < 0x1000u) {
                slot = (uint32_t)(addr >> 11);
                intra = (uint16_t)(addr & 0x07FFu);
            } else {
                slot = 2u + (uint32_t)((addr - 0x1000u) >> 10);
                intra = (uint16_t)(addr & 0x03FFu);
            }
        } else {
            if (addr < 0x1000u) {
                slot = 2u + (uint32_t)(addr >> 10);
                intra = (uint16_t)(addr & 0x03FFu);
            } else {
                slot = (uint32_t)((addr >> 11) & 1u);
                intra = (uint16_t)(addr & 0x07FFu);
            }
        }
        uint32_t bank = (slot < 2u) ? (uint32_t)(c->mmc3_regs[slot] & 0xFEu)
                                    : (uint32_t)c->mmc3_regs[slot];
        offset = (size_t)bank * 0x0400u + intra;
    } else if (c->mapper == 1) {
        uint8_t chr_mode = (uint8_t)((c->mmc1_regs[0] & 0x10u) ? 1u : 0u);
        uint32_t bank = (chr_mode && addr >= 0x1000u) ? c->mmc1_regs[2]
                                                      : c->mmc1_regs[1];
        offset = (size_t)bank * 0x1000u + (addr & 0x0FFFu);
    } else if (c->mapper == 3) {
        offset = (size_t)(c->chr_bank & 3u) * 0x2000u + addr;
    } else {
        offset = addr;
    }
    if (offset < c->chr_size)
        return c->chr[offset];
    return 0;
}

void nes_cart_chr_write(nes_cart *c, uint16_t addr, uint8_t v)
{
    addr &= 0x1FFFu;
    if (!c->chr_ram)
        return; /* CHR ROM: writes ignored */
    size_t offset = addr; /* CHR RAM bank switching for CNROM-with-RAM is a
                             documented limitation; writes go to bank 0 view */
    if (c->mapper == 1) {
        uint8_t chr_mode = (uint8_t)((c->mmc1_regs[0] & 0x10u) ? 1u : 0u);
        uint32_t bank = (chr_mode && addr >= 0x1000u) ? c->mmc1_regs[2]
                                                      : c->mmc1_regs[1];
        offset = (size_t)bank * 0x1000u + (addr & 0x0FFFu);
    }
    if (offset < c->chr_size)
        c->chr[offset] = v;
}
